/* Generated By:JavaCC: Do not edit this line. FLWConstants.java */
package com.example.kotlinspringboot.flw;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FLWConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FOUR_LETTER_WORDS = 1;
  /** RegularExpression Id. */
  int FIVE_OR_MORE_LETTER_WORDS = 2;
  /** RegularExpression Id. */
  int LETTER = 3;
  /** RegularExpression Id. */
  int OTHER = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<FOUR_LETTER_WORDS>",
    "<FIVE_OR_MORE_LETTER_WORDS>",
    "<LETTER>",
    "<OTHER>",
  };

}
