/* Generated By:JavaCC: Do not edit this line. PercentParserConstants.java */
package com.example.kotlinspringboot.parser.percent;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PercentParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 1;
  /** RegularExpression Id. */
  int RBRACE = 2;
  /** RegularExpression Id. */
  int PHASE = 3;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int OTHER = 5;
  /** RegularExpression Id. */
  int COMMENTS = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\"}\"",
    "<PHASE>",
    "<LETTER>",
    "<OTHER>",
    "<COMMENTS>",
  };

}
