/* Generated By:JavaCC: Do not edit this line. SimpleParserConstants.java */
package com.example.kotlinspringboot.parser.simple;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PHASE = 1;
  /** RegularExpression Id. */
  int OPEN_BRACE = 2;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 3;
  /** RegularExpression Id. */
  int OR = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int REPEAT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int OTHER = 8;
  /** RegularExpression Id. */
  int COMMENTS = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<PHASE>",
    "<OPEN_BRACE>",
    "<CLOSE_BRACE>",
    "<OR>",
    "<AND>",
    "<REPEAT>",
    "<LETTER>",
    "<OTHER>",
    "<COMMENTS>",
  };

}
