/* SimpleParser.java */
/* Generated By:JavaCC: Do not edit this line. SimpleParser.java */
package com.example.kotlinspringboot.parser.simple;

import java.io.StringReader;
import java.util.List;

public class SimpleParser extends SimpleParserBase implements SimpleParserConstants {

    public static String simpleParse(String inString) {
        if (inString.equals("")) return "";
        SimpleParser parser = new SimpleParser(new StringReader(inString));
        try {
            return parser.simple();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    final public String simple() throws ParseException {
        List<String> simpleResult;
        simpleResult = expr();
        {
            if ("" != null) return getPartString(simpleResult);
        }
        throw new Error("Missing return statement in function");
    }

    final public List<String> expr() throws ParseException {
        List<String> leftTerm;
        List<String> rightTerm;
        Token concatToken = null;
        leftTerm = wordsOrGroup();
        label_1:
        while (true) {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                case PHASE:
                case OPEN_BRACE:
                case AND: {
                    ;
                    break;
                }
                default:
                    jj_la1[0] = jj_gen;
                    break label_1;
            }
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                case AND: {
                    concatToken = jj_consume_token(AND);
                    break;
                }
                default:
                    jj_la1[1] = jj_gen;
                    ;
            }
            rightTerm = wordsOrGroup();
            leftTerm = getCombinationsOfTwoList(leftTerm, rightTerm, concatToken);
        }
        {
            if ("" != null) return leftTerm;
        }
        throw new Error("Missing return statement in function");
    }

    final public List<String> wordsOrGroup() throws ParseException {
        List<String> leftPhase;
        List<String> rightPhase;
        leftPhase = phaseOrGroup();
        label_2:
        while (true) {
            switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                case OR: {
                    ;
                    break;
                }
                default:
                    jj_la1[2] = jj_gen;
                    break label_2;
            }
            jj_consume_token(OR);
            rightPhase = phaseOrGroup();
            leftPhase = mergeToLeft(leftPhase, rightPhase);
        }
        {
            if ("" != null) return leftPhase;
        }
        throw new Error("Missing return statement in function");
    }

    final public List<String> phaseOrGroup() throws ParseException {
        Token token;
        Token repeat = null;
        List<String> expr;
        switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
            case PHASE: {
                token = jj_consume_token(PHASE);
                switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                    case REPEAT: {
                        repeat = jj_consume_token(REPEAT);
                        break;
                    }
                    default:
                        jj_la1[3] = jj_gen;
                        ;
                }
                {
                    if ("" != null) return singleElementList(token.image, repeat);
                }
                break;
            }
            case OPEN_BRACE: {
                jj_consume_token(OPEN_BRACE);
                expr = expr();
                jj_consume_token(CLOSE_BRACE);
                switch ((jj_ntk == -1) ? jj_ntk_f() : jj_ntk) {
                    case REPEAT: {
                        repeat = jj_consume_token(REPEAT);
                        break;
                    }
                    default:
                        jj_la1[4] = jj_gen;
                        ;
                }
                {
                    if ("" != null) return groupConsiderRepeat(expr, repeat);
                }
                break;
            }
            default:
                jj_la1[5] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
        }
        throw new Error("Missing return statement in function");
    }

    /**
     * Generated Token Manager.
     */
    public SimpleParserTokenManager token_source;
    JavaCharStream jj_input_stream;
    /**
     * Current token.
     */
    public Token token;
    /**
     * Next token.
     */
    public Token jj_nt;
    private int jj_ntk;
    private int jj_gen;
    final private int[] jj_la1 = new int[6];
    static private int[] jj_la1_0;

    static {
        jj_la1_init_0();
    }

    private static void jj_la1_init_0() {
        jj_la1_0 = new int[]{0x26, 0x20, 0x10, 0x40, 0x40, 0x6,};
    }

    /**
     * Constructor with InputStream.
     */
    public SimpleParser(java.io.InputStream stream) {
        this(stream, null);
    }

    /**
     * Constructor with InputStream and supplied encoding
     */
    public SimpleParser(java.io.InputStream stream, String encoding) {
        try {
            jj_input_stream = new JavaCharStream(stream, encoding, 1, 1);
        } catch (java.io.UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
        token_source = new SimpleParserTokenManager(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 6; i++) jj_la1[i] = -1;
    }

    /**
     * Reinitialise.
     */
    public void ReInit(java.io.InputStream stream) {
        ReInit(stream, null);
    }

    /**
     * Reinitialise.
     */
    public void ReInit(java.io.InputStream stream, String encoding) {
        try {
            jj_input_stream.ReInit(stream, encoding, 1, 1);
        } catch (java.io.UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
        token_source.ReInit(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 6; i++) jj_la1[i] = -1;
    }

    /**
     * Constructor.
     */
    public SimpleParser(java.io.Reader stream) {
        jj_input_stream = new JavaCharStream(stream, 1, 1);
        token_source = new SimpleParserTokenManager(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 6; i++) jj_la1[i] = -1;
    }

    /**
     * Reinitialise.
     */
    public void ReInit(java.io.Reader stream) {
        if (jj_input_stream == null) {
            jj_input_stream = new JavaCharStream(stream, 1, 1);
        } else {
            jj_input_stream.ReInit(stream, 1, 1);
        }
        if (token_source == null) {
            token_source = new SimpleParserTokenManager(jj_input_stream);
        }

        token_source.ReInit(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 6; i++) jj_la1[i] = -1;
    }

    /**
     * Constructor with generated Token Manager.
     */
    public SimpleParser(SimpleParserTokenManager tm) {
        token_source = tm;
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 6; i++) jj_la1[i] = -1;
    }

    /**
     * Reinitialise.
     */
    public void ReInit(SimpleParserTokenManager tm) {
        token_source = tm;
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 6; i++) jj_la1[i] = -1;
    }

    private Token jj_consume_token(int kind) throws ParseException {
        Token oldToken;
        if ((oldToken = token).next != null) token = token.next;
        else token = token.next = token_source.getNextToken();
        jj_ntk = -1;
        if (token.kind == kind) {
            jj_gen++;
            return token;
        }
        token = oldToken;
        jj_kind = kind;
        throw generateParseException();
    }


    /**
     * Get the next Token.
     */
    final public Token getNextToken() {
        if (token.next != null) token = token.next;
        else token = token.next = token_source.getNextToken();
        jj_ntk = -1;
        jj_gen++;
        return token;
    }

    /**
     * Get the specific Token.
     */
    final public Token getToken(int index) {
        Token t = token;
        for (int i = 0; i < index; i++) {
            if (t.next != null) t = t.next;
            else t = t.next = token_source.getNextToken();
        }
        return t;
    }

    private int jj_ntk_f() {
        if ((jj_nt = token.next) == null)
            return (jj_ntk = (token.next = token_source.getNextToken()).kind);
        else
            return (jj_ntk = jj_nt.kind);
    }

    private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
    private int[] jj_expentry;
    private int jj_kind = -1;

    /**
     * Generate ParseException.
     */
    public ParseException generateParseException() {
        jj_expentries.clear();
        boolean[] la1tokens = new boolean[10];
        if (jj_kind >= 0) {
            la1tokens[jj_kind] = true;
            jj_kind = -1;
        }
        for (int i = 0; i < 6; i++) {
            if (jj_la1[i] == jj_gen) {
                for (int j = 0; j < 32; j++) {
                    if ((jj_la1_0[i] & (1 << j)) != 0) {
                        la1tokens[j] = true;
                    }
                }
            }
        }
        for (int i = 0; i < 10; i++) {
            if (la1tokens[i]) {
                jj_expentry = new int[1];
                jj_expentry[0] = i;
                jj_expentries.add(jj_expentry);
            }
        }
        int[][] exptokseq = new int[jj_expentries.size()][];
        for (int i = 0; i < jj_expentries.size(); i++) {
            exptokseq[i] = jj_expentries.get(i);
        }
        return new ParseException(token, exptokseq, tokenImage);
    }

    private boolean trace_enabled;

    /**
     * Trace enabled.
     */
    final public boolean trace_enabled() {
        return trace_enabled;
    }

    /**
     * Enable tracing.
     */
    final public void enable_tracing() {
    }

    /**
     * Disable tracing.
     */
    final public void disable_tracing() {
    }

}
